// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIWd7oDINHdSaEqjz0yQQagGeappwvxco',
    appId: '1:236444164733:web:114550e02f43906e290714',
    messagingSenderId: '236444164733',
    projectId: 'ledge-28e07',
    authDomain: 'ledge-28e07.firebaseapp.com',
    storageBucket: 'ledge-28e07.firebasestorage.app',
    measurementId: 'G-0048LJ7CMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzVg9L26BDeSQBJaklvGeDJnS1e5SvADw',
    appId: '1:236444164733:android:d9af0b7b7aab1084290714',
    messagingSenderId: '236444164733',
    projectId: 'ledge-28e07',
    storageBucket: 'ledge-28e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiOrUK1cBc8PkqcihvduCERV8AeCO66Is',
    appId: '1:236444164733:ios:dbc19d28ae8d3623290714',
    messagingSenderId: '236444164733',
    projectId: 'ledge-28e07',
    storageBucket: 'ledge-28e07.firebasestorage.app',
    iosBundleId: 'com.example.ledge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiOrUK1cBc8PkqcihvduCERV8AeCO66Is',
    appId: '1:236444164733:ios:dbc19d28ae8d3623290714',
    messagingSenderId: '236444164733',
    projectId: 'ledge-28e07',
    storageBucket: 'ledge-28e07.firebasestorage.app',
    iosBundleId: 'com.example.ledge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIWd7oDINHdSaEqjz0yQQagGeappwvxco',
    appId: '1:236444164733:web:41baa497f46b47e3290714',
    messagingSenderId: '236444164733',
    projectId: 'ledge-28e07',
    authDomain: 'ledge-28e07.firebaseapp.com',
    storageBucket: 'ledge-28e07.firebasestorage.app',
    measurementId: 'G-XLGG6XZ9TX',
  );

}